INSERT INTO item (
    name, cuisine, description, short_description,
    category, sub_category, item_type,
    base_price, discount, on_sale, currency,
    available, out_of_stock, seasonal,
    image, recipe,
    rating, rating_count, view_count, sold_count,
    is_signature, is_featured, is_top_rated,
    menu_id, hidden, notes,
    created_at, created_by,
    updated_at, updated_by
) VALUES
(
    'Pizza Napoletana', 'IT',
    'Traditional Neapolitan pizza with tomato sauce, mozzarella di bufala, and basil.',
    'Classic Neapolitan pizza.',
    'Food', 'Pizza', 'FOOD',
    12.00, 0, 0, 'USD',
    1, 0, 0,
    'pizza-napoletana.jpg', NULL,
    4.6, 120, 500, 300,
    1, 1, 1,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Pizza Margherita', 'IT',
    'Fresh tomato sauce, mozzarella, basil, and olive oil.',
    'Simple and iconic.',
    'Food', 'Pizza', 'FOOD',
    10.00, 0, 0, 'USD',
    1, 0, 0,
    'pizza-margherita.jpg', NULL,
    4.7, 200, 700, 450,
    1, 1, 1,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Pepperoni Pizza', 'IT',
    'Mozzarella cheese and spicy pepperoni slices.',
    'Best-selling classic.',
    'Food', 'Pizza', 'FOOD',
    11.50, 0, 0, 'USD',
    1, 0, 0,
    'pepperoni-pizza.jpg', NULL,
    4.8, 300, 900, 650,
    0, 1, 1,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Calzone Pizza', 'IT',
    'Folded pizza stuffed with mozzarella, ricotta, and ham.',
    'Stuffed Italian calzone.',
    'Food', 'Pizza', 'FOOD',
    13.00, 0, 0, 'USD',
    1, 0, 0,
    'calzone-pizza.jpg', NULL,
    4.4, 80, 300, 200,
    0, 0, 0,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Caprese Pizza', 'IT',
    'Tomato, fresh mozzarella, basil, and olive oil.',
    'Light and fresh.',
    'Food', 'Pizza', 'FOOD',
    11.00, 0, 0, 'USD',
    1, 0, 0,
    'caprese-pizza.jpg', NULL,
    4.5, 90, 320, 210,
    0, 0, 0,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Sicilian Pizza', 'IT',
    'Thick crust pizza with rich tomato sauce and cheese.',
    'Square thick-crust pizza.',
    'Food', 'Pizza', 'FOOD',
    14.00, 0, 0, 'USD',
    1, 0, 0,
    'sicilian-pizza.jpg', NULL,
    4.3, 70, 250, 180,
    0, 0, 0,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Pizza Marinara', 'IT',
    'Tomato sauce, garlic, oregano, and olive oil.',
    'Vegan traditional pizza.',
    'Food', 'Pizza', 'FOOD',
    9.50, 0, 0, 'USD',
    1, 0, 0,
    'pizza-marinara.jpg', NULL,
    4.2, 60, 220, 160,
    0, 0, 0,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Pizza Primavera', 'IT',
    'Seasonal vegetables, mozzarella, and tomato sauce.',
    'Vegetable-rich pizza.',
    'Food', 'Pizza', 'FOOD',
    12.50, 0, 0, 'USD',
    1, 0, 0,
    'pizza-primavera.jpg', NULL,
    4.4, 85, 280, 190,
    0, 0, 0,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Pizza Quattro Formaggi', 'IT',
    'Mozzarella, gorgonzola, parmesan, and fontina cheese.',
    'Four cheese delight.',
    'Food', 'Pizza', 'FOOD',
    13.50, 0, 0, 'USD',
    1, 0, 0,
    'pizza-quattro-formaggi.jpg', NULL,
    4.7, 140, 420, 310,
    1, 0, 1,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
),
(
    'Pizza Capricciosa', 'IT',
    'Ham, mushrooms, olives, artichokes, and mozzarella.',
    'Rich topping combination.',
    'Food', 'Pizza', 'FOOD',
    13.00, 0, 0, 'USD',
    1, 0, 0,
    'pizza-capricciosa.jpg', NULL,
    4.6, 110, 360, 260,
    0, 0, 1,
    1, 0, NULL,
    CURRENT_TIMESTAMP, 'system',
    CURRENT_TIMESTAMP, 'system'
);
